### ISSUE TITLE
Ids have changed

### ISSUE THREAD

**Issue by jahire2** [AB1908/GOG-Galaxy-Export-Script#1]
Hi the org values for gamePieceTypeId are not working.

It worked when I updated them to
dataId1 = 21
dataId2 = 9
titleId1 = 10
titleId2 = 23

I am in NA. Might be a region thing.

**Comment by AB1908** [comment]
That actually makes a lot of sense. Thanks for pointing it out. To help me out, verify this by executing a query:

```
sqlite3> select * by GamePieceType;
```

This table appears to contain the relevant `gamePieceTypeId`. If it does contain the appropriate values by region, you can go ahead an open a pull request to fix this.

**Comment by jahire2** [comment]
Here you go
id	type
1	myRating
4	myAchievementsCount
5	allGameReleases
6	dlcs
7	media
8	originalImages
9	originalMeta
10	originalTitle
11	osCompatibility
21	meta
22	summary
23	title
6099	myFriendsActivity
6115	friendsOwning
6663	changelog
6664	goodies
6665	isPreorder
6666	productLinks

May be make another DB call at the start to get these values and then append them to your next query.

BTW great work on the script, its super helpful. Its 2020 and still I don't have a good way to filter and sort my game list :)

**Comment by AB1908** [comment]
Great, this'll do the trick. Do you want to have a go at it? It's roughly 15 minutes of work.

**Comment by jahire2** [comment]
k sure will update it today

**Comment by AB1908** [comment]
Okay then. Let me know if you run into trouble.

**Comment by jahire2** [comment]
Ready with the change. I'll need push access.

**Comment by AB1908** [comment]
The way you should do it is open a Pull Request using a separate branch and push to it. That way, we can review it and make changes as necessary. Hopefully, this doesn't come off as condescending. It's just the way it should be done and this is the procedure usually followed for any open source project. Open a pull request by comparing across forks. In case you haven't forked the project, go ahead and do so and push your changes to your own fork.

**Comment by jahire2** [comment]
sure no issues. haven't worked much on open source before.

**Comment by AB1908** [comment]
Great job opening your first issue and PR. Thanks a lot for the help!
