### ISSUE TITLE
Game titles with a forward slash have it escaped

### ISSUE THREAD

**Issue by toastmonster** [AB1908/GOG-Galaxy-Export-Script#10]
Example --
"Rising Storm/Red Orchestra 2 Multiplayer" is listed as "Rising Storm\/Red Orchestra 2 Multiplayer"

**Comment by AB1908** [comment]
Err, isn't this correct?

**Comment by AB1908** [comment]
Apparently it's not. It's listed as "Rising Storm\\/Red Orchestra 2 Multiplayer".
