### ISSUE TITLE
It seems GOG changed game table name

### ISSUE THREAD

**Issue by zooglea** [AB1908/GOG-Galaxy-Export-Script#14]
Thanks for this script!

It seems in the new beta update the table name for games has changed from **OwnedGames** to **GameLinks**.

**Comment by toastmonster** [comment]
Yeah was about to comment on this one.  

```
Traceback (most recent call last):
  File "galaxy_library_export.py", line 38, in <module>
    cursor.execute(aggr_game_data)
sqlite3.OperationalError: no such table: OwnedGames
```

**Comment by toastmonster** [comment]
Did a simple Search and Replace on my copy of the script and it worked.

**Comment by AB1908** [comment]
Wow you guys really are on top of this! Anyone picking it up?

**Comment by toastmonster** [comment]
I was looking into, but couldn't work out how I make a branch, or a fork, or a pull request, or whatever it was I needed to do.  I'll leave that to someone who knows how.

**Comment by AB1908** [comment]
In case you're eager to do it, I'd be glad to help you out with this. If you aren't particularly interested, that's cool too. What about you @zooglea ?

**Comment by toastmonster** [comment]
Not eager at all, personally.  😂

**Comment by toastmonster** [comment]
OK I did a thing, but I wanted to link this Issue to my code, but I don't think I can.  Think you might have to do it, @AB1908

**Comment by zooglea** [comment]
I've updated script and I created a pull request.
