### ISSUE TITLE
sqlite3.OperationalError

### ISSUE THREAD

**Issue by toastmonster** [AB1908/GOG-Galaxy-Export-Script#19]
Traceback (most recent call last):
  File "galaxy_library_export.py", line 39, in <module>
    cursor.execute(owned_game_filtered_data)
sqlite3.OperationalError: near ")": syntax error

**Comment by AB1908** [comment]
Could you check the brackets on the queries in line 30-31? I'm certain this worked on my system before I pushed it.

**Comment by toastmonster** [comment]
Can't see anything wrong.  There appears to be the right number of opening and closing brackets (using Notepad++ to show the pairing) so I have no suggestions, sorry.

**Comment by AB1908** [comment]
Was able to reproduce. Let me see where I goofed.
