### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by toastmonster** [AB1908/GOG-Galaxy-Export-Script#20]
Traceback (most recent call last):
  File "galaxy_library_export.py", line 52, in <module>
    row['title'] = result[1].split('"')[3]
IndexError: list index out of range

**Comment by AB1908** [comment]
I think I ought to give up programming.

**Comment by AB1908** [comment]
Weird, can't reproduce this one. Could you figure out where it fails? I'm assuming there's a game you have that has a double quote in it, which I honestly never expected. I originally thought of using regex to parse the title but eventually decided against it.

**Comment by AB1908** [comment]
Adding a potential fix to the branch with your name. Try it out.

**Comment by toastmonster** [comment]
It is actually dropping a gameDB.csv file, and it looks complete to me.  Maybe it doesn't like game titles with a comma in the name?
[gameDB.zip](https://github.com/AB1908/GOG-Galaxy-Export-Script/files/4567366/gameDB.zip)

**Comment by AB1908** [comment]
Off topic but sweet lord what a collection. Nice :+1:.

**Comment by AB1908** [comment]
Could you name which games have been dropped?

**Comment by toastmonster** [comment]
Sorry, I meant "dropped" as "created".  It's creating the csv file.
