### ISSUE TITLE
ModuleNotFoundError: No module named 'natsort'

### ISSUE THREAD

**Issue by toastmonster** [AB1908/GOG-Galaxy-Export-Script#25]
The current release does not work.

> python galaxy_library_export.py
> 
> Traceback (most recent call last):
>   File "galaxy_library_export.py", line 7, in <module>
>     from natsort import natsorted
> ModuleNotFoundError: No module named 'natsort'

**Comment by toastmonster** [comment]
Oh never mind, user error.  RTFM.  Fixed by running "pip install natsort".

**Comment by AB1908** [comment]
Indeed! The readme states that we need a new dependency `natsort`. Go ahead and install this using `pip install natsort` in your terminal of choice. I realise now that this should be in the readme so I'll get around to adding it.

The tool has been rewritten by a fellow contributor and is somewhat more complex to use. Based on your feedback, I could write a better guide for it, if you could find the time.

If you wish to use an older version, simply browse through the commit history and find the one you'd like to use.
