### ISSUE TITLE
How to link the platform to releaseKey from the DB file? 

### ISSUE THREAD

**Issue by DisgruntledJarl** [AB1908/GOG-Galaxy-Export-Script#27]
I have been taking a look at the code and want to write a simpler version for myself from scratch with the final objective of generating a random game picker. 

After looking through the db file, I have a rough idea on how to get the Title of the game, the tags, release date etc. I do not know how to get the platform. Is there a field in any of the tables that links the platform to the releaseKey? Or are you figuring out the platform using the first few characters of the Release Key?

**Comment by AB1908** [comment]
You may want to go back 3 commits to 900dc18 to a simpler version of the script.

As for obtaining the platform, I'm using the latter. The `releaseKey` often is of the type `platform_gameID` so I did a simple check for it. You also may want to look at the wiki if you need more info on the queries that I have used. There may be better ways of doing this but this was all the info I could scrap together.

**Comment by DisgruntledJarl** [comment]
Thanks. The wiki [Query](https://github.com/AB1908/GOG-Galaxy-Export-Script/wiki/Query ) page is very useful. Helped me a lot. I would suggest moving the platform variable to a text file and reading it from there. Might seem more complicated but it would be easier to add newer platforms and increases modularity.

**Comment by AB1908** [comment]
Fair point. I'll make that improvement sometime. Thanks for the feedback.

**Comment by AB1908** [comment]
You may also want to use a random picker another user created here:

https://github.com/zooglea/GOG-Galaxy-Export-Script

Note that it is several commits behind and you may have to pull commits from my repo. I never accepted this into the repo as I felt it was unnecessary.
