### ISSUE TITLE
platformList inaccurate

### ISSUE THREAD

**Issue by toastmonster** [AB1908/GOG-Galaxy-Export-Script#3]
Products owned in the GOG store are shown as owned in "Placeholder".  Products owned on Twitch are usually shown as being owned on additional platforms, example "Twitch,Itch.io" or "Twitch,Itch.io,BlackBerry Games??".  Products owned in Humble Bundle are usually shown as being owned on additional platforms, example "Humble Bundle,Nintendo DS" or "Humble Bundle,Steam,Nintendo Entertainment System".

**Comment by AB1908** [comment]
The Humble Bundle Keys require some more logic, I definitely agree there. It's a byproduct of how they name their keys. For example, if I have a Steam key on HB, it's labeled something like `humble_witcher_3_steam`. I'll think of a way to fix this and am also open to suggestions. As for Twitch products, I'm not sure. Could you find the relevant releaseKey for an idea of why it's bugging out? I'll take a look at the GOG entries.

**Comment by AB1908** [comment]
Oh, it looks like while updating the platform list, I just kinda skipped GOG. Fixing.

**Comment by AB1908** [comment]
Ah I think I know how to fix the Humble Bundle parsing. I should use `startsWith`. I'll fix this and push it after a little testing.

**Comment by AB1908** [comment]
@toastmonster : Could you pull my fix branch to test if it works?

**Comment by toastmonster** [comment]
@AB1908 PlatformList looks accurate to me now, good job!

**Comment by AB1908** [comment]
Haha this was going to be autoclosed by the PR. Ya didn't have to close it.
