### ISSUE TITLE
At least 1 game missing from export

### ISSUE THREAD

**Issue by toastmonster** [AB1908/GOG-Galaxy-Export-Script#32]
I noticed that my export using the latest release is missing at least one game.

You'll notice in the screenshot below that I have all 5 episodes of "3 out of 10" from Epic Games Store, yet the exported file is missing episode 2, "Foundation 101".

![missing game](https://user-images.githubusercontent.com/6852402/96350910-063ece80-10b0-11eb-9d15-eba6f30db098.png)

**Comment by toastmonster** [comment]
It's definitely not there in the raw export file either, by the way.

**Comment by Varstahl** [comment]
Episode 2 is in the CSV but there's something wrong, on that you're right.

**Comment by AB1908** [comment]
This looks like an interesting bug. @Varstahl, can I have a crack at it?

**Comment by Varstahl** [comment]
3 out of 10 episode 2 is counted as DLC for Episode 1. Apparently Epic switched mid release. We need special rulesets for it I think, if we can actually do anything. @AB1908 sure thing, I was about to look into the DB myself, go on.

**Comment by AB1908** [comment]
I'll look into it in a few hours. Thanks for the quick debug info!

**Comment by Varstahl** [comment]
I went ahead 'cause the curiosity got the best of me, and as I was supposing a dirty fix requires a single line of code. A few more if we want to do things better, in case this problem returns.

I'm not spoiling the solution though, it's a good exercise to familiarise with the codebase :)

**Comment by toastmonster** [comment]
Perhaps an optional switch to include (or exclude) DLC?

**Comment by Varstahl** [comment]
@AB1908 the fix is ready to be merged (#33), along with the export by default you requested previously (#30) and the ability to now sort the export data as the user wants, by keeping track of the user modified `sortingTitle` (#34).
