### ISSUE TITLE
Platform not being populated

### ISSUE THREAD

**Issue by techdesign** [AB1908/GOG-Galaxy-Export-Script#37]
I ran the script and ended up with a spreadsheet that appears to list all of the games, but the platform column is almost empty. It has a few entries, but the vast majority are blank.

I am on Windows 10, using Python 3.9.1. I did notice that my switches appear to not be honored (using -o c:\temp\gog.csv and it still comes out as gamesdb.csv for instance) so perhaps I am just doing something wrong?

I've attached part of my CSV file if that helps.
[games - Copy.zip](https://github.com/AB1908/GOG-Galaxy-Export-Script/files/5730823/games.-.Copy.zip)

**Comment by techdesign** [comment]
Okay, hold on a sec...I think it was just an idiot move on my part. I tried opening the file directly via Excel and it mangled the layout, so I did convert text to columns, which showed me the empty platform.

When I started with an empty workbook and did "get data from text/csv" it came in properly and looks fine.

Sorry for the false alarm.

**Comment by AB1908** [comment]
Do you have any error messages or output from the terminal to share? I've noticed a few weird errors on my end as well but haven't investigated them yet.

**Comment by AB1908** [comment]
Ah, no issues! Feel free to suggest any improvements or other errors!
