### ISSUE TITLE
Request / Question: export isHidden or isVisibleInLibrary attribute

### ISSUE THREAD

**Issue by fcgooner** [AB1908/GOG-Galaxy-Export-Script#42]
Can you add export of isHidden/isVisibleInLibrary attribute from UserReleaseProperties/ReleaseProperties table (not sure which one is identifies if game is hidden in library)?

**Comment by TheMelmacian** [comment]
_isHidden_ is the correct flag.
_isVisibleInLibrary_ is used internally by the Galaxy Client to hide items which shouldn't be displayed in the library at all. For example some DLCs, Soundtracks, Tools like Source Filmmaker (via Steam import) and even a few Games.

There is already a pull request https://github.com/AB1908/GOG-Galaxy-Export-Script/pull/38 which adds the isHidden flag to the export, but AB1908 hasn't reviewed it yet.

**Comment by AB1908** [comment]
I'm so sorry. I haven't had the time to get around to this but I look forward to reviewing it soon!

**Comment by TheMelmacian** [comment]
No problem ;) Take your time.

**Comment by fcgooner** [comment]
> _isHidden_ is the correct flag.
> _isVisibleInLibrary_ is used internally by the Galaxy Client to hide items which shouldn't be displayed in the library at all. For example some DLCs, Soundtracks, Tools like Source Filmmaker (via Steam import) and even a few Games.
> 
> There is already a pull request #38 which adds the isHidden flag to the export, but AB1908 hasn't reviewed it yet.

Oh, I've missed it.
Well, it's good news for me then :)
Thanks for this addition!

P.S. Closing the issue
