### ISSUE TITLE
Double game listing bug

### ISSUE THREAD

**Issue by AB1908** [AB1908/GOG-Galaxy-Export-Script#5]
Some games are listed twice because of certain factors. For example, Alan Wake has separate release dates for Epic Games Launcher and Steam. I'm not sure if this is intentional to denote different release dates on different platforms but it causes the `GROUP BY` query to fail as the metadata column is not unique. Any suggestions for fixes are welcome.

**Comment by toastmonster** [comment]
Not sure how to fix it as I'm not a programmer, but I have attached the dupes that show up from my library.

It does appear that the different entries have different release dates, but the developers and publishers are the same, so perhaps some sort of logic that if the name is the same, and the developers and publishers are also the same, then combine it?

[dupes.xlsx](https://github.com/AB1908/GOG-Galaxy-Export-Script/files/4477015/dupes.xlsx)

**Comment by AB1908** [comment]
I thought of that initially. I'll have to try it out and see how viable it is.

**Comment by toastmonster** [comment]
Of course, if both the developers and publishers are also blank, then I guess you'd have to fall back to comparing genres and themes.

**Comment by toastmonster** [comment]
There also appears to be code in the GUI that deals with games that may have different punctuation on different stores.  Alan Wake(')s American Nightmare, for example.  

![Annotation 2020-04-14 202706](https://user-images.githubusercontent.com/6852402/79265749-7dd83a80-7e8e-11ea-9f01-c2eb43bb2a4c.png)

And some games with different capitalisation, for example BIT.TRIP Runner.

![Annotation 2020-04-14 202923](https://user-images.githubusercontent.com/6852402/79265896-b5df7d80-7e8e-11ea-9af7-2ea52752bbd0.png)

**Comment by AB1908** [comment]
> There also appears to be code in the GUI that deals with games that may have different punctuation on different stores. Alan Wake(')s American Nightmare, for example.
> 
> ![Annotation 2020-04-14 202706](https://user-images.githubusercontent.com/6852402/79265749-7dd83a80-7e8e-11ea-9f01-c2eb43bb2a4c.png)
> 
> And some games with different capitalisation, for example BIT.TRIP Runner.
> 
> ![Annotation 2020-04-14 202923](https://user-images.githubusercontent.com/6852402/79265896-b5df7d80-7e8e-11ea-9af7-2ea52752bbd0.png)

Those differences in titles are due to the way naming is done on the respective platforms. I'd rather use a single name and be done with it. Perhaps in a future version, a toggle could be included for what kind of result the user wants.

> Of course, if both the developers and publishers are also blank, then I guess you'd have to fall back to comparing genres and themes.

You know, looking for edge cases is coming more naturally to you than it is to me. Perhaps you should programming a chance. 😄

As for the double listing, I've had some ideas and I'll test them some more.

**Comment by toastmonster** [comment]
Before running the comparison of the names, you should do a LOWER() on the values, that should then match them regardless of case.

Not sure how to deal with titles with different punctuation depending on the store.  There may be a function to remove punctuation before doing the compare.
