### ISSUE TITLE
GOG Galaxy 2.0.44.218 broke exporting

### ISSUE THREAD

**Issue by lemondjeff** [AB1908/GOG-Galaxy-Export-Script#52]
GOG Galaxy updated itself to version 2.0.44.218 today and appears to have removed the `GameLinks` table from the database schema. I see the following error when running the export script now:

```
Traceback (most recent call last):
  File "galaxy_library_export.py", line 605, in <module>
    extractData(args)
  File "galaxy_library_export.py", line 359, in extractData
    cursor.execute(unique_game_data)
sqlite3.OperationalError: no such table: GameLinks
```

I last ran the export script against a database created by GOG Galaxy 2.0.43.71 near the end of October 2021 and it was working with no problems. Unfortunately, since GOG Galaxy uses a stub installer which always installs the latest version, I don't see any way to downgrade it as a workaround.

**Comment by TheMelmacian** [comment]
@lemondjeff You can update your script manually ([see changes](https://github.com/AB1908/GOG-Galaxy-Export-Script/pull/53/files)), if you don't want to wait for the merge.

**Comment by AB1908** [comment]
Ayy, sorry.

**Comment by TheMelmacian** [comment]
No problem ;)

**Comment by lemondjeff** [comment]
Thank you!
