### ISSUE TITLE
Get the "gameId" of GOG games

### ISSUE THREAD

**Issue by josue2363** [AB1908/GOG-Galaxy-Export-Script#55]
Hi, I'm sorry if I'm doing this in the wrong place or if someone has already arrived with this same issue, I really didn't find it.

Would it be possible to get the "gameId" of GOG games?

**Comment by AB1908** [comment]
Hey, did you figure this out? Sorry for not replying earlier.

**Comment by josue2363** [comment]
Hi, thanks for replying. I still haven't figured it out. I don't have much experience with python or database. If you can help with that, I would be very grateful. My idea is to do something like:

wine start "C:\Program Files (x86)\GalaxyClient\GalaxyClient.exe" /gameId=1495134320 /command=runGame /path="F:\josue\Gog\The Witcher 3 Wild Hunt GOTY"

Where the game id would be in the "gameId=" option.

**Comment by AB1908** [comment]
I'll give this a try.
