### ISSUE TITLE
How to...

### ISSUE THREAD

**Issue by Chaleff** [AB1908/GOG-Galaxy-Export-Script#61]
It would be appreciated if you included a simple guide about how to actually use the script. For those who are clueless. You're just assuming everyone who reads the description will understand everything :X

**Comment by AB1908** [comment]
I know and I'm quite sorry! Which part do you specifically need help with?

**Comment by Chaleff** [comment]
Everything, I guess? I've looked up information on how to run a github/python script.
Downloaded python 3.11 and git 2.38 and github desktop, yet still when I try to run galaxy_library_export.py I'm either getting a black command line window for 1 second and then it disappears, or getting this: "SyntaxError: unexpected character after line continuation character"

**Comment by AB1908** [comment]
I did try and keep an initial user friendly version but it has gotten out of hand. How urgent is this? I'll try and make time accordingly but most likely towards the weekend.

Also, please look into Playnite. It connects many different libraries and exports as CSV as a core feature. I currently use that instead.

**Comment by Chaleff** [comment]
It is not urgent at all. I will check Playnite and return here to tell you if I got what I needed, perhaps I won't need any help at all :)
Thank you for the quick responses though!

**Comment by Chaleff** [comment]
Playnite has worked wonderfully. I just wish it had the option to include each game's link to their respective platform store page, but that's too much to ask I guess :D
Thank you for mentioning it!
