### ISSUE TITLE
Help Functionality Not Working

### ISSUE THREAD

**Issue by Mikowmer** [AB1908/GOG-Galaxy-Export-Script#63]
Whenever I try to get the help page from the script, I get the following error:

```
Traceback (most recent call last):
  File "galaxy_library_export.py", line 578, in <module>
    'default': defaultDBlocation,
NameError: name 'defaultDBlocation' is not defined
```

I've tried this by using `python3 galaxy_library_export.py`, `python3 galaxy_library_export.py -h` and `python3 galaxy_library_export.py --help`. It appears that the argument in galaxy_library_export.py for help isn't set properly. (line 573 for quick lookup)

**Comment by Varstahl** [comment]
What platform is it running from? Linux? MacOS? Windows?

**Comment by Mikowmer** [comment]
... Ubuntu running on Windows Subsystem for Linux. I think that might be what's causing it... 🤦‍♂️

I just tried running it in PowerShell and it worked fine. This isn't an issue with help so much as one dealing with it running at all apparently.
