### ISSUE TITLE
csv file has blank lines between every row

### ISSUE THREAD

**Issue by toastmonster** [AB1908/GOG-Galaxy-Export-Script#7]
The csv file appears to have each line terminated by a CR, followed by a CRLF.  This causes a blank line to appear between each row.

![Annotation 2020-04-14 184137](https://user-images.githubusercontent.com/6852402/79256265-9ab94180-7e7f-11ea-9823-d73971f0b711.png)

**Comment by AB1908** [comment]
Is this causing import problems? I saw this too but I just assumed that it was supposed to be that way.

**Comment by toastmonster** [comment]
I can sort the sheet which moves the blank rows to the end but that's a workaround rather than a fix.  Low priority.

**Comment by AB1908** [comment]
Okay, I'll take a look. Probably something to do with the write CSV row method.
