### ISSUE TITLE
Entries with no release date in the DB appear with today's date in the CSV

### ISSUE THREAD

**Issue by toastmonster** [AB1908/GOG-Galaxy-Export-Script#9]
Noticed a number of games show as having today as their release date (and one with a date in the future but that's probably bad data in the DB)

Checked with the Galaxy2 GUI and it appears to coincide with entries that have no release date.

**Comment by AB1908** [comment]
Yup, you're right. I forgot to add edge cases for `None` types which indicate date is missing. You're pretty good with investigating.
